Made the mission statement page
JaviChip/R-Group pull request #28
Opened 2024-02-16 12:38 UTC by arnavswami

Made mission statement page. Small message and image of 1431 Everton Place on both sides. Let me know if you think that there should be any changes or if the styling should be different.

2024-02-17 07:20 UTC, arnavswami commented
![Image 2-16-24 at 11 18 PM](https://github.com/JaviChip/R-Group/assets/68790299/80f5bf3b-18cb-4b59-a22f-86d2f47a627a)

2024-02-18 00:11 UTC, JaviChip commented on src/components/home/Mission.jsx
> +            }}
Dont use Style , thats CSS . Use TailwindCSS inline

2024-02-18 00:14 UTC, JaviChip requested changes

2024-02-18 00:14 UTC, JaviChip commented on src/components/home/Mission.jsx
> +            <span style={{ fontFamily: "Arial, sans-serif", fontSize: "22px" }}>
Dont use Style , use tailwindCSS

2024-02-18 02:09 UTC, JaviChip commented on src/components/home/Mission.jsx
> +      <div className="w-1/12"></div>
is this for spacing between the paragraph and image ?

2024-02-18 02:10 UTC, JaviChip commented on src/components/home/Mission.jsx
> +        <Image alt="" src={image1} className="ml-4 mr-auto" />
Add an alt text for eslint purposes

2024-02-18 02:10 UTC, JaviChip commented on src/components/home/Mission.jsx
> +          <div className="w-1/6"></div>
what does this do ?

2024-02-18 20:05 UTC, JaviChip approved these changes

2024-02-18 20:05 UTC, merged